services:
  # aspnet-dk24ttc6-luuthingoc-cafeshop:
  #   image: aspnet-dk24ttc6-luuthingoc-cafeshop
  #   build:
  #     context: .
  #     dockerfile: ASPNET-DK24TTC6-LuuThiNgoc-CafeShop/Dockerfile
  #   depends_on:
  #     - sqlserver-cafeshop

  sqlserver-cafeshop:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver-cafeshop
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1234qwer##"
    ports:
      - "1433:1433"

